Chore/python 3 12 1
mindsightbr/django-background-tasks pull request #8
Opened 2024-01-05 20:05 UTC by camposmoreira

2024-01-12 15:10 UTC, Caiofcas commented on background_task/tasks.py
> +            import_module('tasks', package=app)
Acho que tinha um problema com isso na versão antiga quando você passava o app como `"myapp.apps.MyAppConfig"` no `INSTALLED_APPS`. Essas mudanças corrigem isso tbm?

2024-01-12 15:35 UTC, camposmoreira commented on background_task/tasks.py
> +            import_module('tasks', package=app)
Não cheguei a testar este caso. Saindo das reuniões testo ele e informo

2024-01-15 13:28 UTC, diksown requested changes

2024-01-15 13:28 UTC, diksown commented on Dockerfiles/commands.md
> +docker run -it p352
```suggestion
docker build -f Dockerfiles/Dockerfile.3.5.2 -t p35 . --progress=plain
docker build -f Dockerfiles/Dockerfile.3.10 -t p310 . --progress=plain
docker build -f Dockerfiles/Dockerfile.3.11 -t p311 . --progress=plain
docker build -f Dockerfiles/Dockerfile.3.12 -t p312 . --progress=plain
docker run -it p35
```

Para manter a padronização, se não os outros parecem `3.1.2` e não `3.12`

2024-01-15 13:28 UTC, diksown commented on Dockerfiles/commands.md
Seria legal colocar isso num CI/CD, não?
Se quiser, posso ajudar com isso.

2024-02-26 14:00 UTC, camposmoreira commented
DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

2025-07-04 19:26 UTC, merged

2025-07-07 14:45 UTC, Caiofcas commented
:partying_face: